name: necrobiome
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - r::r-base=3.6.1
  - bioconda::cutadapt=2.10
  - bioconda::seqtk=1.3
  - bioconda::mafft=7.471
  - bioconda::fasttree=2.1.10
